name: "BowlingSim"
# sim-mode: "Frame-by-frame"
# sim-mode: "AFAP"
time-step: 1e-3
end-time: 50
solver-iters: 1

logging: False
logging-output-folder: "../output/convergence"
logging-interval: 10
log-residuals: True

hdr-image-filename: "../resource/studio_1k.hdr"
create-skybox: False
hdr-scaling: 0.3
exposure: 0.2

camera-focal-point: [0, 0.1, 0]
camera-position: [4, 0.5, 0]

ground-plane: False
rod-rod-collisions: True

hash-voxel-size: 1e-1
num-hash-buckets: 31111

# uncomment to save video
window-width: 2000
window-height: 2000
render-for-video: True
render-output-folder: "../output/render/bowling_teaser"
fps: 10

# objects: