name: "SuturingSim"

# by default, the sim attempts to run in real-time
# sim-mode: "Frame-by-frame"      # uncomment this line to run the simulation "frame by frame" (press any key on the keyboard to step forward one time step)
# sim-mode: "AFAP"                # uncomment this line to run the simulation "As Fast As Possible"

time-step: 5e-4                   # the time step used by the sim
end-time: 100000                  # the end time in the sim (some large number)

# logging - leave disabled
logging: False
logging-output-folder: "../output/convergence"
logging-interval: 10
log-residuals: True

# simulating render settings
hdr-image-filename: "../resource/studio_1k.hdr"
create-skybox: True
hdr-scaling: 0.3

ground-plane: True                # whether or not to create a ground plane

camera-focal-point: [0, 0, 0]
camera-position: [120, 15, 0]
camera-orthographic: False

# objects:
