name: "RodSim"
# sim-mode: "Frame-by-frame"
# sim-mode: "AFAP"
time-step: 1e-4
end-time: 10

logging: False
logging-output-folder: "../output/convergence"
logging-interval: 10
log-residuals: True

hdr-image-filename: "../resource/studio_1k.hdr"
create-skybox: True
hdr-scaling: 0.2

ground-plane: True

render-for-video: True

objects:
  - 
    type: "Rod"
    name: "rod1"
    element-type: "Linear"
    initial-position: [0, 1, 0.0]
    initial-rotation: [0, 90, 0]
    E: 5e6
    nu: 0.4
    beta: 1e2
    diameter: 0.1
    length: 1
    density: 1000
    elements: 10
    global-solve: true
    base-fixed: True
    tip-fixed: False
    collisions: False
    log-particles: True
    render-type: "PBR"
    smooth-normals: True
    # orm-texture-filename: "../resource/textures/Metal050A_4K-PNG/Metal050A_4K-PNG_ORM.png"
    # base-color-texture-filename: "../resource/textures/Metal050A_4K-PNG/Metal050A_4K-PNG_Color.png"
    metallic: 0.0
    roughness: 0.5
    color: [1.0, 0, 0]
    opacity: 1
    draw-centerline: False
    centerline-samples: 50
    draw-end-caps: True
    

  # - 
  #   type: "Rod"
  #   name: "rod1"
  #   element-type: "Quadratic"
  #   initial-position: [0, 1, 0.0]
  #   initial-rotation: [0, 90, 0]
  #   E: 5e6
  #   nu: 0.4
  #   diameter: 0.1
  #   length: 1
  #   density: 1000
  #   elements: 10
  #   base-fixed: True
  #   tip-fixed: False
  #   collisions: False
  #   log-particles: True
  #   render-type: "PBR"
  #   # orm-texture-filename: "../resource/textures/Metal050A_4K-PNG/Metal050A_4K-PNG_ORM.png"
  #   # base-color-texture-filename: "../resource/textures/Metal050A_4K-PNG/Metal050A_4K-PNG_Color.png"
  #   metallic: 0.0
  #   roughness: 0.5
  #   color: [0, 0, 1.0]

  # - 
  #   type: "Rod"
  #   name: "rod1"
  #   element-type: "Cubic"
  #   initial-position: [0, 1, 0.0]
  #   initial-rotation: [0, 90, 0]
  #   E: 5e6
  #   nu: 0.4
  #   diameter: 0.1
  #   length: 1
  #   density: 1000
  #   elements: 5
  #   base-fixed: True
  #   tip-fixed: False
  #   collisions: False
  #   log-particles: True
  #   render-type: "PBR"
  #   # orm-texture-filename: "../resource/textures/Metal050A_4K-PNG/Metal050A_4K-PNG_ORM.png"
  #   # base-color-texture-filename: "../resource/textures/Metal050A_4K-PNG/Metal050A_4K-PNG_Color.png"
  #   metallic: 0.0
  #   roughness: 0.5
  #   color: [0, 1.0, 0]

# precurved spring
  # - 
  #   type: "Rod"
  #   name: "rod2"
  #   element-type: "Quadratic"
  #   initial-position: [0, 1.3, 0]
  #   initial-rotation: [90, 90, 0]
  #   elements: 100
  #   E: 1e6
  #   diameter: 0.02
  #   length: 2
  #   nu: 0.3
  #   curvature: [0,30,-7]
  #   base-fixed: True
  #   tip-fixed: False
  #   render-type: "PBR"
  #   # orm-texture-filename: "../resource/textures/Metal050A_4K-PNG/Metal050A_4K-PNG_ORM.png"
  #   # base-color-texture-filename: "../resource/textures/Metal050A_4K-PNG/Metal050A_4K-PNG_Color.png"
  #   metallic: 0.0
  #   roughness: 0.5
  #   color: [0.0, 0.0, 1.0]

  # - 
  #   type: "Rod"
  #   name: "rod2"
  #   element-type: "Cubic Hermite"
  #   initial-position: [0.2, 1, 0.0]
  #   initial-rotation: [0, 0, 0]
  #   E: 5e6
  #   nu: 0.4
  #   diameter: 0.1
  #   length: 1
  #   density: 1000
  #   elements: 5
  #   global-solve: True
  #   base-fixed: True
  #   tip-fixed: False
  #   collisions: False
  #   log-particles: True
  #   render-type: "PBR"
  #   # orm-texture-filename: "../resource/textures/Metal050A_4K-PNG/Metal050A_4K-PNG_ORM.png"
  #   # base-color-texture-filename: "../resource/textures/Metal050A_4K-PNG/Metal050A_4K-PNG_Color.png"
  #   metallic: 0.0
  #   roughness: 0.5
  #   color: [1.0, 0, 0]

  # -
  #   type: "RigidBox"
  #   name: "sphere1"
  #   initial-position: [0,0,0]
  #   initial-velocity: [0,0,0]
  #   render-type: "PBR"
  #   metallic: 0.2
  #   roughness: 0.5
  #   color: [1.0, 1.0, 1.0]