name: "Plectoneme Sim"
# sim-mode: "Frame-by-frame"
# sim-mode: "AFAP"
time-step: 1e-2
solver-iters: 100
end-time: 1000

camera-focal-point: [0,10,0]
# camera-position: [0.25,1.5,4]
camera-position: [10,20,10]

logging: False
logging-output-folder: "../output/rps_robot"
logging-interval: 0.01
log-residuals: True

hdr-image-filename: "../resource/studio_1k.hdr"
create-skybox: True

ground-plane: True

objects:
  -
    type: "Plectoneme"
    revolutions: 4

    color: [1.0, 0.5, 0.0]