name: "RPS Sim"
# sim-mode: "Frame-by-frame"
sim-mode: "AFAP"
time-step: 1e-3
end-time: 10
solver-iters: 1

camera-focal-point: [0,0,0]
# camera-position: [0.25,1.5,4]
camera-position: [2,1.5,2]

logging: True
logging-output-folder: "../output/rps_robot"
logging-interval: 0.01
log-residuals: True

hdr-image-filename: "../resource/studio_1k.hdr"
create-skybox: True

ground-plane: True

objects:
  -
    type: "RPSRobot"
    log-particles: False

    use-normed-constraints: False
    projector-type: "separate"

    color: [1.0, 0.5, 0.0]