name: "Rod convergence"
# sim-mode: "Frame-by-frame"
sim-mode: "AFAP"
time-step: 1e-2
end-time: 100

ground-plane: False

E: 5e6
nu: 0.4
diameter: 0.1
length: 1
density: 1000

# rigid-body-rod-elements: [5, 10, 20, 40, 80, 160]
# linear-rod-elements: [2, 5, 10, 20, 40, 80, 160]
# quadratic-rod-elements: [1, 2, 5, 10, 20, 40, 80, 160]
cubic-hermite-rod-elements: [1, 2, 4, 8, 16]

# rigid-body-rod-elements: [5, 10, 20]
# linear-rod-elements: [5, 10, 20]
# quadratic-rod-elements: [5, 10, 20]

# simulation render settings
hdr-image-filename: "../resource/studio_1k.hdr"
create-skybox: True